version: '3' 
services:   
  database:
      container_name: mysql
      image: mysql:5.7
      environment:
        MYSQL_HOST: "localhost"
        MYSQL_ROOT_PASSWORD: "12345678"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "12345678"
        MYSQL_DATABASE: "wakoky"
      ports:
        - "3306:3306"
      restart: unless-stopped
      volumes:
        - ./mysql/db_data:/var/lib/mysql
        - ./wakoky.sql:/docker-entrypoint-initdb.d/wakoky.sql
  web:
    container_name: myserver
    build:
      context: ./phpapache
    volumes:
      - ./certificates:/etc/apache2/ssl_keys
      - ./phpapache/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database    
    links:
      - database
    tty: true